export type ProjectCategory =
    | "Apps & Tools"
    | "Documents"
    | "Data & Analysis"
    | "Creative"
    | "Others";

export interface Project {
    id: string;
    title: string;
    description_short: string; // Used in card view
    description: string; // Used in modal view (long text)
    category: ProjectCategory;
    thumbnail_url: string;
    project_url?: string; // Optional: Some projects might not have a link
    creator_name: string;
    creator_x_id?: string; // e.g. "CyberArtist_99" (without @)
    creator_x_url?: string; // Full URL
    status: "approved";
}

export const PROJECTS: Project[] = [
    {
        id: "1",
        title: "Neon Tokyo Dream",
        description_short: "A cyberpunk city exploration experience generated entirely by AI.",
        description: "Neon Tokyo Dream is an immersive visual experience that takes you on a journey through a futuristic, cyberpunk-inspired Tokyo. Every texture, building model, and atmospheric effect was conceptualized and refined using advanced generative AI models. The project aims to explore the boundaries between synthetic creativity and human curation, offering a glimpse into a world where technology and tradition blend seamlessly under neon lights.",
        category: "Creative",
        thumbnail_url: "/images/art-01.png",
        project_url: "https://example.com/art1",
        creator_name: "CyberArtist_99",
        creator_x_id: "CyberArtist_99",
        creator_x_url: "https://x.com/example",
        status: "approved",
    },
    {
        id: "2",
        title: "CodeVisualizer Pro",
        description_short: "Visualize your codebase structure in 3D. Built with React Three Fiber.",
        description: "CodeVisualizer Pro transforms flat directory structures into stunning 3D visualizations. By analyzing file dependencies and folder hierarchies, it creates a navigable cityscape of your code. This tool is designed to help developers understand large legacy codebases quickly, identifying complex modules and potential refactoring targets through visual intuition.",
        category: "Apps & Tools",
        thumbnail_url: "/images/tool-01.png",
        project_url: "https://example.com/tool1",
        creator_name: "DevToolsInc",
        creator_x_id: "DevToolsInc",
        creator_x_url: "https://x.com/devtools",
        status: "approved",
    },
    {
        id: "3",
        title: "Forest Quest: Legacy",
        description_short: "A retro-style RPG adventure. Assets and dialogue generated by LLMs.",
        description: "Forest Quest: Legacy is a love letter to 16-bit RPGs, but with a twist: all dialogue, item descriptions, and quest lines are generated dynamically by Large Language Models. This allows for infinite replayability and unique NPC interactions that feel fresh every time. The visual assets were also crafted using style-consistent image generation techniques.",
        category: "Creative",
        thumbnail_url: "/images/game-01.png",
        project_url: "https://example.com/game1",
        creator_name: "RetroGamer",
        creator_x_id: "RetroGamer_JP",
        creator_x_url: "https://x.com/retrogamer",
        status: "approved",
    },
    {
        id: "4",
        title: "Neural Network Viz",
        description_short: "Interactive educational tool for understanding neural weights.",
        description: "Understanding deep learning can be abstract and difficult. Neural Network Viz offers an interactive playground where students can manipulate weights and biases in real-time to see how they affect network output. Perfect for classrooms and self-learners wanting to build an intuition for backpropagation and activation functions.",
        category: "Data & Analysis",
        thumbnail_url: "/images/tool-01.png",
        project_url: "https://example.com/util1",
        creator_name: "AI_Researcher",
        status: "approved",
    },
    {
        id: "5",
        title: "Midnight City",
        description_short: "Atmospheric looping animation of a rainy city street.",
        description: "A never-ending loop of a rainy midnight street, accompanied by lo-fi beats generated by AI audio models. This project serves as a perfect background companion for studying or relaxing. The visual loop is seamless, created using video diffusion models to ensure perfect continuity.",
        category: "Creative",
        thumbnail_url: "/images/art-01.png",
        project_url: "https://example.com/art2",
        creator_name: "CityScaper",
        creator_x_id: "CityScaper",
        creator_x_url: "https://x.com/cityscaper",
        status: "approved",
    },
    {
        id: "6",
        title: "AI Trends Report 2025",
        description_short: "Comprehensive analysis of AI adoption trends in enterprise.",
        description: "This document compiles data from over 500 companies to analyze how AI is reshaping various industries. Contains predictive models for 2026 and deep dives into sector-specific challenges. Generated with the assistance of data analysis agents.",
        category: "Documents",
        thumbnail_url: "/images/tool-01.png",
        creator_name: "Analyst_Dave",
        status: "approved",
    },
];
